<?php foreach($app->getAssets()->getJs() as $js) { ?>
    <script type="text/javascript" src="<?php echo $js; ?>"></script>
<?php } ?>
<?php if ( $app->getInfos()->hasConfig('google') ) { 
    $google =  $app->getInfos()->getConfig('google');
    if ( !empty($google['analytics']) ) {
?>
    <script type="text/javascript">
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', '<?php echo $google['analytics']; ?>']);
      _gaq.push(['_setDomainName', '<?php echo $_SERVER['HTTP_HOST']; ?>']);
      _gaq.push(['_setAllowLinker', true]);
      _gaq.push(['_trackPageview']);
      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();
    </script>
<?php } } ?>