    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="description" content="<?php echo $app->getInfos()->getDescription(); ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?php echo $app->getInfos()->getTitle(); ?></title>
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <?php foreach($app->getAssets()->getCss() as $css) { ?>
    <link rel="stylesheet" href="<?php echo $css; ?>" />
    <?php } ?>