<?php /* @var $data Exception */ ?>
<div class="page-header">
    <h1>
        <?php echo dgettext('core', 'An unexpected error occurred'); ?>
        <small><?php echo dgettext('core', 'Internal Server Error'); ?></small>
    </h1>
</div>
<p>
    <strong>
        <?php echo $data->getMessage(); ?>
    </strong>
</p>
<?php if ( CAN_DEBUG ) { ?>
<hr />
<h2><?php echo dgettext('core', 'See the following details :'); ?></h2>
<pre><code><?php
    echo($data);
?></code></pre>
<?php } ?>